name: ROS2 CI
on: push
jobs:
  build:
    runs-on: ${{matrix.runs-on}}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-18.04, ubuntu-20.04, windows-latest, macos-latest]
        use_local_repos: ["", "use_local_repos"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: |
            git config --global --add remote.origin.fetch "+refs/pull/*:refs/remotes/origin/pull/*/merge"
      - uses: ros-tooling/setup-ros@master
      # - run: python -m pip install --upgrade pip setuptools wheel
      # - run: pip install --upgrade colcon-common-extensions vcstool
      - if: ${{matrix.use_local_repos}}
        run: echo "::set-env name=additional_repo_url::${{github.workspace}}/local.repos"
      - uses: ros-tooling/action-ros-ci@master
        with:
          vcs-repo-file-url: |
            "https://github.com/ros2/ros2/raw/master/ros2.repos" 
            ${{env.additional_repo_url}}
          package-name: rmw_cyclonedds_cpp
          target-ros2-distro: rolling
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            ros_ws/log/
            ros_ws/build/
