name: ROS2 CI
on: push
jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install --upgrade --user colcon-common-extensions vcstool
      - run: python my_script.py
      - shell: bash
        run: mkdir -p ros2/src
      - run: vcs import ros2/src --input https://github.com/ros2/ros2/raw/master/ros2.repos
      # Runs a set of commands using the runners shell
      - run: colcon build --merge
        working-directory: ros2/src
