name: ROS2 CI
on: push
jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: pip install --upgrade colcon-common-extensions vcstool
      - shell: python
        run: |
          from pathlib import Path
          Path('ros2/src').mkdir(parents=True, exist_ok=True)
      - uses: actions/setup-msbuild@v1.0.1
      - working-directory: ros2
        run: |
          vcs import src --input https://github.com/ros2/ros2/raw/master/ros2.repos
          colcon build --merge
        
