name: ROS2 CI
on: push
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        vcs-repo-file-url:
          - [https://github.com/ros2/ros2/raw/master/ros2.repos]
          - [https://github.com/ros2/ros2/raw/master/ros2.repos, ./local/repos]
        use-local-repos: [false, true]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: |
            git config --global --unset-all remote.origin.fetch
            git config --global --add remote.origin.fetch "+refs/pull/*:refs/remotes/origin/pull/*"
      - uses: ros-tooling/setup-ros@master
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: pip install --upgrade colcon-common-extensions vcstool
      - uses: ros-tooling/action-ros-ci@master
        with:
          vcs-repo-file-url: ${{matrix.vcs-repo-file-url}}
          package-name: rmw_cyclonedds_cpp
